on: [push]

jobs:
  local_test_inside_home:
    runs-on: ubuntu-latest
    env:
      BATS_LIB_PATH: "./mypath"
    name: local default inside home
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0
      - name: Setup Bats-libs
        uses: ./
        with:
          bats-lib-path: "mypath"
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute test to check Bats-detik
        run: |
          cd /tmp/bats-detik/
          bats tests
      - name: Execute test to check Bats-file
        # Currently the bats-file tests are broken
        # in gh runner env
        continue-on-error: true
        run: |
          cd /tmp/bats-file/
          bats test
  local_test_inside_workspace:
    needs: [local_test_inside_home]
    runs-on: ubuntu-latest
    env:
      BATS_LIB_PATH: "${{ github.workspace }}/test"
    name: local default inside home
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0
      - name: Setup Bats-libs
        uses: ./
        with:
          bats-lib-path: "${{ github.workspace }}/test"
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute test to check Bats-detik
        run: |
          cd /tmp/bats-detik/
          bats tests
      - name: Execute test to check Bats-file
        # Currently the bats-file tests are broken
        # in gh runner env
        continue-on-error: true
        run: |
          cd /tmp/bats-file/
          bats test
